Pin 2278 - Add parsing interface utils and new Digester
pagopa/interop-commons pull request #244
Opened 2022-12-15 10:50 UTC by beetlecrunch

2022-12-15 10:53 UTC, beetlecrunch commented on utils/src/main/scala/it/pagopa/interop/commons/utils/Digester.scala
> +  def toMD5[A](value: A)(implicit digester: Digester[A]): String = digester.toMD5(value)
This function must be applied to catalog-management

2022-12-15 13:32 UTC, galales approved these changes
Minor comments but LGTM.

I wonder if it could be worth to create a different module.
Very few services will use these new features, but all of them depends on `utils` and will carry the additional dependencies

2022-12-15 13:32 UTC, galales commented on utils/src/test/scala/it/pagopa/interop/commons/utils/InterfaceParserSpec.scala
> +  }
shouldn't these go under `"InterfaceParser"`?

2022-12-15 13:32 UTC, galales commented on utils/src/test/resources/api.json
> +      "url": "http://petstore.swagger.io/api"
it could be worth to add multiple urls to improve testing cases (same for yaml and soap)

2022-12-16 08:13 UTC, TonioGela commented on build.sbt
> -ThisBuild / resolvers += Resolver.githubPackages("pagopa")
???

2022-12-16 08:14 UTC, TonioGela commented on build.sbt
> -ThisBuild / resolvers += Resolver.githubPackages("pagopa")
This PR is merging in 1.0.x, are you sure the destination branch is the correct one?

2022-12-16 08:14 UTC, TonioGela commented on build.sbt
> +  }
same as before

2022-12-16 08:15 UTC, TonioGela commented on build.sbt
> -  .enablePlugins(NoPublishPlugin)
This should stay

2022-12-16 08:16 UTC, TonioGela commented on parser/src/main/scala/it/pagopa/interop/commons/parser/InterfaceParser.scala
> +  def parseSoap(bytes: Array[Byte]): Either[Throwable, Elem] = {
I would call it `parseWSDL` since the other is called `parseOpenApi` and not `parseYAML`

2022-12-16 08:17 UTC, TonioGela commented on parser/src/main/scala/it/pagopa/interop/commons/parser/InterfaceParserUtils.scala
> +  def getUrls[A](serviceInterface: A)(implicit ie: InterfaceParserUtils[A]): Either[Throwable, List[String]] =
```suggestion
  def getUrls[A: InterfaceParserUtils](serviceInterface: A): Either[Throwable, List[String]] =
```

2022-12-16 08:17 UTC, TonioGela commented on parser/src/main/scala/it/pagopa/interop/commons/parser/InterfaceParserUtils.scala
> +  def getEndpoints[A](serviceInterface: A)(implicit ie: InterfaceParserUtils[A]): Either[Throwable, List[String]] =
```suggestion
  def getEndpoints[A: InterfaceParserUtils](serviceInterface: A): Either[Throwable, List[String]] =
```

2022-12-16 08:22 UTC, TonioGela requested changes

2022-12-16 08:22 UTC, TonioGela commented on parser/src/main/scala/it/pagopa/interop/commons/parser/errors/Errors.scala
> +      extends Throwable(s"Error trying to extract some information from interface document")
```suggestion
      extends Exception(s"Error trying to extract some information from interface document")
```

2022-12-16 08:22 UTC, TonioGela commented on utils/src/main/scala/it/pagopa/interop/commons/utils/Digester.scala
> +  }
implicit defs are a anti-pattern in Scala and have a few documented use cases in which they're fundamental, why are we using them here, taking in consideration that they're not even methods but values without an input?

2022-12-19 11:02 UTC, TonioGela approved these changes

2022-12-19 11:08 UTC, merged